
services:
  flask-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8880:5000
    volumes:
      - ./:/flask-simple-app
    image: flask-server:0.5
    restart: unless-stopped
  nginx:
    ports:
      - 8680:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - /etc/letsencrypt/live/soundcollectflask.com/fullchain.pem:/cert/fullchain.pem
      # - /etc/letsencrypt/live/soundcollectflask.com/privkey.pem:/cert/privkey.pem
      # - /etc/letsencrypt/options-ssl-nginx.conf:/cert/options-ssl-nginx.conf
    image: nginx
    restart: unless-stopped


